<a href="https://colab.research.google.com/github/Balajiibe/Guvi/blob/main/Copy_of_Numpy_tasks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy



#### 1. Import the numpy package under the name `np` (★☆☆) 
(**hint**: import … as …)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆) 
(**hint**: np.\_\_version\_\_, np.show\_config)

In [4]:
print(np.__version__)
np.show_config

<function numpy.__config__.show()>

#### 3. Create a null vector of size 10 (★☆☆) 
(**hint**: np.zeros)

In [6]:
ar=np.zeros(10)
ar

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4.  How to find the memory size of any array (★☆☆) 
(**hint**: size, itemsize)

In [7]:
ar.size

10

#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆) 
(**hint**: np.info)

In [9]:
# np.info
help(np.add)

Help on ufunc object:

add = class ufunc(builtins.object)
 |  Functions that operate element by element on whole arrays.
 |  
 |  To see the documentation for a specific ufunc, use `info`.  For
 |  example, ``np.info(np.sin)``.  Because ufuncs are written in C
 |  (for speed) and linked into Python with NumPy's ufunc facility,
 |  Python's help() function finds this page whenever help() is called
 |  on a ufunc.
 |  
 |  A detailed explanation of ufuncs can be found in the docs for :ref:`ufuncs`.
 |  
 |  **Calling ufuncs:** ``op(*x[, out], where=True, **kwargs)``
 |  
 |  Apply `op` to the arguments `*x` elementwise, broadcasting the arguments.
 |  
 |  The broadcasting rules are:
 |  
 |  * Dimensions of length 1 may be prepended to either array.
 |  * Arrays may be repeated along dimensions of length 1.
 |  
 |  Parameters
 |  ----------
 |  *x : array_like
 |      Input arrays.
 |  out : ndarray, None, or tuple of ndarray and None, optional
 |      Alternate array object(s) in whic

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆) 
(**hint**: array\[4\])

In [10]:
arr=np.zeros(10)
arr[4]=1
arr

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆) 
(**hint**: np.arange)

In [12]:
arr=np.arange(10,49)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

#### 8.  Reverse a vector (first element becomes last) (★☆☆) 
(**hint**: array\[::-1\])

In [13]:
arr=arr[::-1]
arr

array([48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32,
       31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15,
       14, 13, 12, 11, 10])

#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆) 
(**hint**: reshape)

In [14]:
arr=np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆) 
(**hint**: np.nonzero)

In [17]:
NonZero=[i for i,x in enumerate ([1,2,0,0,4,0] ) if x != 0]
NonZero


[0, 1, 4]

#### 11. Create a 3x3 identity matrix (★☆☆) 
(**hint**: np.eye)

In [20]:
ar=np.identity(3,dtype= 'int')
ar

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

#### 12. Create a 3x3x3 array with random values (★☆☆) 
(**hint**: np.random.random)

In [21]:
arr=np.random.rand(3,3,3)
arr

array([[[0.18464007, 0.53290535, 0.77655231],
        [0.50202854, 0.43645799, 0.58789211],
        [0.18782398, 0.61255683, 0.61147689]],

       [[0.46847316, 0.16129622, 0.33647956],
        [0.24629119, 0.2645779 , 0.17399342],
        [0.07769808, 0.29221942, 0.98159355]],

       [[0.85191102, 0.75654718, 0.16105642],
        [0.61118656, 0.53641124, 0.76867375],
        [0.10743628, 0.90660568, 0.58202754]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆) 
(**hint**: min, max)

In [24]:
ar=np.random.rand(10,10)
ar
print(ar.min())
ar.max()

0.003584500357991627


0.9854623377670247

#### 14. Create a random vector of size 30 and find the mean value (★☆☆) 
(**hint**: mean)

In [26]:
arr=np.random.rand(30)
arr.mean()


0.37225415466728545

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆) 
(**hint**: array\[1:-1, 1:-1\])

In [27]:
arr = np.ones((5,5),dtype = 'int')
arr[1:-1,1:-1] = np.zeros((3,3),dtype = 'int')
arr

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆) 
(**hint**: np.pad)

In [35]:
arr = np.random.rand(5,5)
arr_size = np.array(arr.shape)+2
arr_1 = np.zeros(arr_size,dtype = 'float')
arr_1[1:-1,1:-1] = arr[:,:]
arr_1arr = np.random.random((5,5))
arr = np.pad(arr,pad_width=((​1,1)​),mode = 'constant'​,constant_values = 0)
arr

SyntaxError: ignored

#### 17. What is the result of the following expression? (★☆☆) 
(**hint**: NaN = not a number, inf = infinity)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

In [37]:
False

False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆) 
(**hint**: np.diag)

In [38]:
arr = np.diag((1,2,3,4))
arr = np.pad(arr,pad_width = ((1,0),(0,1)),mode = 'constant')
arr

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆) 
(**hint**: array\[::2\])

In [41]:
arr = np.zeros((8,8),dtype = 'int')
# arr[::2,1::2] = arr[1::2,::2] = arr
arr

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 
(**hint**: np.unravel_index)

In [47]:
arr = np.arange(​6​,7​​).reshape(​6​,​7​,​8​)
arr[1,5,3]

SyntaxError: ignored

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆) 
(**hint**: np.tile)

In [ ]:
arr = np.array([[0,1],
               [1,0]])
arr = np.tile(arr,(4,4))
arr

#### 22. Normalize a 5x5 random matrix (★☆☆) 
(**hint**: (x - min) / (max - min))

In [49]:
arr = np.random.random((​5​,​5​)).astype(​'d'​)
arr_max,arr_min = arr.max(),arr.min()
arr = (arr-arr_min)/(arr_max - arr_min)
print(arr)
print(arr.dtype)

SyntaxError: ignored

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆) 
(**hint**: np.dtype)

In [50]:
RGBA = np.dtype([(​'red'​,np.uint8),(​'green'​,np.uint8),(​'blue'​,np.uint8),(​'alpha'​,np.uint8)])
color = np.array((1,2,4,3),dtype = RGBA)
print(color['red'])
type(color)

SyntaxError: ignored

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆) 
(**hint**: np.dot | @)

In [51]:
arr_1 = np.random.random((5,3))
arr_2 = np.random.random((3,2))
print(arr_1 @ arr_2)
np.dot(arr_1,arr_2)

[[1.2217952  0.25751231]
 [1.85146648 0.44680444]
 [1.44482037 0.31217067]
 [0.80532101 0.20816722]
 [1.06524397 0.251702  ]]


array([[1.2217952 , 0.25751231],
       [1.85146648, 0.44680444],
       [1.44482037, 0.31217067],
       [0.80532101, 0.20816722],
       [1.06524397, 0.251702  ]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆) 
(**hint**: >, <=)

In [53]:
arr = np.arange(16)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

#### 26. What is the output of the following script? (★☆☆) 
(**hint**: np.sum)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [54]:
9
10

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [58]:

Z<Z>Z

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
nan
not a Arry
Integers

#### 29. How to round away from zero a float array ? (★☆☆) 
(**hint**: np.uniform, np.copysign, np.ceil, np.abs)

In [62]:
arr = np.random.rand(5,5)
print(arr)
arr = np.round(arr,2)
print(arr) 

[[0.02964182 0.33781414 0.2845253  0.31597564 0.16563948]
 [0.59130539 0.67477272 0.24279453 0.66659955 0.38174147]
 [0.69366109 0.51832886 0.77794077 0.44793374 0.46298619]
 [0.9506038  0.52607296 0.08851816 0.49608995 0.13209791]
 [0.12074849 0.28771855 0.00166445 0.39130231 0.40448574]]
[[0.03 0.34 0.28 0.32 0.17]
 [0.59 0.67 0.24 0.67 0.38]
 [0.69 0.52 0.78 0.45 0.46]
 [0.95 0.53 0.09 0.5  0.13]
 [0.12 0.29 0.   0.39 0.4 ]]


#### 30. How to find common values between two arrays? (★☆☆) 
(**hint**: np.intersect1d)

In [64]:
arr_1 = np.arange(9).reshape(3,3)
arr_2 = np.array([[0,1,2],[3,4,5],[1,1,1]])
indices = [i for i,x,y in enumerate(arr_1,arr_2) if (x ==y) ]
indices = (arr_1 == arr_2)
indices



TypeError: ignored

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆) 
(**hint**: np.seterr, np.errstate)

In [68]:
defaults = np.seterr(all="ignore")
defaults_TN= np.seterr(**defaults)

#### 32. Is the following expressions true? (★☆☆) 
(**hint**: imaginary number)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [70]:
False

False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆) 
(**hint**: np.datetime64, np.timedelta64)

In [75]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today     = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print(yesterday,today,tomorrow, sep=' / ')

2022-09-22 / 2022-09-23 / 2022-09-24


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆) 
(**hint**: np.arange(dtype=datetime64\['D'\]))

In [76]:
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆) 
(**hint**: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))

In [83]:

A = np.ones(3)*1
B = np.ones(3)*2

​x=np.add(A,B,out=B)
y=np.divide(A,2,out=A)
z=np.negative(A,out=A)
w=np.dot(A,B)

SyntaxError: ignored

#### 36. Extract the integer part of a random array using 5 different methods (★★☆) 
(**hint**: %, np.floor, np.ceil, astype, np.trunc)

In [89]:
Z = np.random.random((​0​,​​10​))
Z
print (Z - Z%1)
print (np.floor(Z))
print (np.ceil(Z)-1)
print (Z.astype(int))

SyntaxError: ignored

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆) 
(**hint**: np.arange)

In [92]:
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)
# z=np.arange(0,4).reshape(5,5)
# print(z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆) 
(**hint**: np.fromiter)

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆) 
(**hint**: np.linspace)

In [93]:
Z = np.linspace(​0​,​1​,​11​,endpoint=​False​)[​1​:]
print(Z)

SyntaxError: ignored

#### 40. Create a random vector of size 10 and sort it (★★☆) 
(**hint**: sort)

In [94]:
Z = np.random.random(10)
Z.sort()
print(Z)

[0.12265586 0.29309791 0.33913405 0.34538701 0.39019205 0.67010489
 0.81862162 0.85661392 0.94320046 0.958306  ]


#### 41. How to sum a small array faster than np.sum? (★★☆) 
(**hint**: np.add.reduce)

In [100]:
import numpy as np
import functools as ft
Z = np.arange(10)
np.add.reduce(Z)
# ​ft.reduce(np.add,Z,​0​)
# Z

45

#### 42. Consider two random array A and B, check if they are equal (★★☆) 
(**hint**: np.allclose, np.array\_equal)

In [103]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
print(A,B)
equal = np.allclose(A,B)
print(equal)
equal = np.array_equal(A,B)
print(equal)

[1 0 1 1 0] [0 1 0 1 0]
False
False


#### 43. Make an array immutable (read-only) (★★☆) 
(**hint**: flags.writeable)

In [106]:
Z = np.zeros(10)
Z.flags.writeable = False
# Z[0] = 1

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆) 
(**hint**: np.sqrt, np.arctan2)

In [110]:
z= np.random.randint(​0​,​9​,(​10​,​2​))
x,y = z[:,0], z[:,1]
r = np.sqrt(x**2+y**2)
t = np.arctan2(y,x)
poles = np.c_[r,t]
poles

SyntaxError: ignored

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆) 
(**hint**: argmax)

In [112]:
arr = np.random.random(10)
# print(arr)
arr[arr.argmax()] = 0
arr

array([0.47473437, 0.35560793, 0.        , 0.50509206, 0.38621335,
       0.43549232, 0.93504159, 0.82429078, 0.95360499, 0.54170129])

#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆) 
(**hint**: np.meshgrid)

SyntaxError: ignored

####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) 
(**hint**: np.subtract.outer)

In [117]:
X = np.random.randint(0,11,(5,5))
# X = np.random.randint(​11​,​22​,​10​)
Y = np.tile(X,(10,1))
X  = np.tile(X,(10,1))
C = 1/(X - Y)
#print(Y.reshape(1,10))Y = np.tile(Y,(10,1))
#print(X)X  = np.tile(X,(10,1)).T
#print(X)C = 1/(X - Y)
C

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: RuntimeWarning: divide by zero encountered in true_divide
  """


array([[inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, i

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆) 
(**hint**: np.iinfo, np.finfo, eps)

In [118]:
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆) 
(**hint**: np.set\_printoptions)

In [119]:
z=[1,2,3]
z

[1, 2, 3]

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆) 
(**hint**: argmin)

In [121]:
arr = np.random.uniform(​0​,(​10​,​10​))
scal = 5
arr_1 = np.abs(arr - 5)
ind = arr_1.argmin()
print(arr)
print('*'*60)
print(arr[ind])


SyntaxError: ignored

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆) 
(**hint**: dtype)

In [122]:
Z = np.zeros(10, [ ('position', [ ('x', float),
                                  ('y', float)]),
                   ('color',    [ ('r', float),
                                  ('g', float),
                                  ('b', float)])])
print(Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆) 
(**hint**: np.atleast\_2d, T, np.sqrt)

In [124]:
arr = np.random.random((​100​,​2​))
X,Y = np.atleast_2d(arr[:,​0​],arr[:,​1​])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
# Much faster with scipyimport scipy
# Thanks Gavin Heverly-Coulson (#issue 1)import scipy.spatial
Z = np.random.random((​10​,​2​))
D = scipy.spatial.distance.cdist(Z,Z)
print(D)

SyntaxError: ignored

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place? 
(**hint**: astype(copy=False))

In [126]:
Z = np.arange(10, dtype=np.float32)
Z_1 = Z.astype(np.float32, copy=False)
Z_1[0] = 2
print(Z)

[2. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 54. How to read the following file? (★★☆) 
(**hint**: np.genfromtxt)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [128]:
from io import StringIO
s = StringIO("""1, 2, 3, 4, 5\n
              6,  ,  , 7, 8\n
              ,  , 9,10,11\n""")
Z = np.genfromtxt(s, delimiter=",", dtype=np.int)
print(Z)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  """


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆) 
(**hint**: np.ndenumerate, np.ndindex)

In [130]:
Z = np.arange(​0,9​).reshape(​3​,​3​)
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])

SyntaxError: ignored

#### 56. Generate a generic 2D Gaussian-like array (★★☆) 
(**hint**: np.meshgrid, np.exp)

In [131]:
sigma,myu = 1.0,0.0X,Y  = np.meshgrid(np.linspace(-​1​,​1​,​10​),np.linspace(-​1​,​1​,​10​))
D = np.sqrt(X**2+Y**2)
G = np.exp(-(D-myu)**​2​/(​2​*sigma**​2​))
print(G)

SyntaxError: ignored

#### 57. How to randomly place p elements in a 2D array? (★★☆) 
(**hint**: np.put, np.random.choice)

In [133]:
n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print(Z)
np.put(Z,11,1)
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆) 
(**hint**: mean(axis=,keepdims=))

In [134]:
X = np.random.rand(5, 10)
Y = X - X.mean(axis = 1,keepdims = True)
print(Y)
X.mean(axis = 1).reshape(-1,1) == X.mean(axis = 1,keepdims =True)

[[ 0.06478271 -0.05113866 -0.10392767  0.29733792 -0.14068836 -0.19804204
  -0.20884926  0.49233509  0.07171609 -0.22352583]
 [ 0.13759787  0.04422544  0.10566217  0.29737713 -0.41496095  0.45665726
  -0.3052162  -0.43196456  0.46439859 -0.35377674]
 [ 0.01675276  0.33806338 -0.13719601 -0.21705078  0.2880186   0.326114
   0.14649252 -0.40834495  0.1708274  -0.52367691]
 [-0.21089394  0.37373402 -0.18948223  0.06435879 -0.58981999  0.01001806
   0.19884158  0.12469029  0.0784669   0.14008652]
 [ 0.19440012  0.26299036 -0.43078158 -0.02009217  0.26143665  0.25505915
   0.15569872  0.00162176 -0.12596288 -0.55437013]]


array([[ True],
       [ True],
       [ True],
       [ True],
       [ True]])

#### 59. How to sort an array by the nth column? (★★☆) 
(**hint**: argsort)

In [135]:
Z = np.random.randint(​0​,​10​,(​5​,​5​))
print(Z)
# Z_1 = Z# for ind in range(5):#     Z_1[:,ind].sort()​#print(Z_1)​print​(Z[(-Z)[:,​1​].argsort()])
print(Z[:,Z[1,:].argsort()])

SyntaxError: ignored

#### 60. How to tell if a given 2D array has null columns? (★★☆) 
(**hint**: any, ~)

In [136]:
Z = np.random.randint(​0​,​3​,(​3​,​10​))
Z[:,1] = 0Z = Z.astype(bool)
print(Z)
print(~Z)
(Z).any(axis = 0)

SyntaxError: ignored

#### 61. Find the nearest value from a given value in an array (★★☆) 
(**hint**: np.abs, argmin, flat)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆) 
(**hint**: np.nditer)

#### 63. Create an array class that has a name attribute (★★☆) 
(**hint**: class method)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★) 
(**hint**: np.bincount | np.add.at)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★) 
(**hint**: np.bincount)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★) 
(**hint**: np.unique)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★) 
(**hint**: sum(axis=(-2,-1)))

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★) 
(**hint**: np.bincount)

#### 69. How to get the diagonal of a dot product? (★★★) 
(**hint**: np.diag)

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★) 
(**hint**: array\[::4\])

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★) 
(**hint**: array\[:, :, None\])

#### 72. How to swap two rows of an array? (★★★) 
(**hint**: array\[\[\]\] = array\[\[\]\])

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★) 
(**hint**: repeat, np.roll, np.sort, view, np.unique)

#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★) 
(**hint**: np.repeat)

#### 75. How to compute averages using a sliding window over an array? (★★★) 
(**hint**: np.cumsum)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★) 
(**hint**: from numpy.lib import stride_tricks)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★) 
(**hint**: np.logical_not, np.negative)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★) 
(**hint**: minimum, maximum)

#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★) 
(**hint**: stride\_tricks.as\_strided)

#### 82. Compute a matrix rank (★★★) 
(**hint**: np.linalg.svd) (suggestion: np.linalg.svd)

#### 83. How to find the most frequent value in an array? 
(**hint**: np.bincount, argmax)

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★) 
(**hint**: stride\_tricks.as\_strided)

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★) 
(**hint**: class method)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★) 
(**hint**: np.tensordot)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★) 
(**hint**: np.add.reduceat)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★) 
(**hint**: np.argsort | np.argpartition)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★) 
(**hint**: np.indices)

#### 91. How to create a record array from a regular array? (★★★) 
(**hint**: np.core.records.fromarrays)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★) 
(**hint**: np.power, \*, np.einsum)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★) 
(**hint**: np.where)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★) 
(**hint**: np.unpackbits)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★) 
(**hint**: np.ascontiguousarray)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★) 
(**hint**: np.einsum)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)? 
(**hint**: np.cumsum, np.interp)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★) 
(**hint**: np.logical\_and.reduce, np.mod)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★) 
(**hint**: np.percentile)